export const carStores = [
	{
		_id: 1,
		logo: "./image/acura_logo.png",
		image: "./image/acura.png",
		product: "Acura",
		count: 1,
		price: 3000,
	},
	{
		_id: 2,
		logo: "./image/alfa_romeo_logo.png",
		image: "./image/alfa_romeo.png",
		product: "Alfa Romeo",
		count: 1,
		price: 5000,
	},
	{
		_id: 3,
		logo: "./image/aston_martin_logo.png",
		image: "./image/aston_martin.png",
		product: "Aston martin",
		count: 1,
		price: 11500,
	},
	{
		_id: 4,
		logo: "./image/bentley_logo.png",
		image: "./image/bentley.png",
		product: "Bentley",
		count: 1,
		price: 6500,
	},
	{
		_id: 5,
		logo: "./image/bmw_logo.png",
		image: "./image/bmw.png",
		product: "Bmw",
		count: 1,
		price: 5000,
	},
	{
		_id: 6,
		logo: "./image/bugatti_logo.png",
		image: "./image/bugatti.png",
		product: "bugatti",
		count: 1,
		price: 9500,
	},
	{
		_id: 7,
		logo: "./image/cadillac_logo.png",
		image: "./image/cadillac.png",
		product: "Cadillac",
		count: 1,
		price: 11000,
	},
	{
		_id: 8,
		logo: "./image/chrysler_logo.png",
		image: "./image/chrysler.png",
		product: "Chrysler",
		count: 1,
		price: 10500,
	},
	{
		_id: 9,
		logo: "./image/citroen_logo.png",
		image: "./image/citroen.png",
		product: "Citroen",
		count: 1,
		price: 2500,
	},
	{
		_id: 10,
		logo: "./image/daewoo_logo.png",
		image: "./image/daewoo.png",
		product: "Daewoo",
		count: 1,
		price: 4000,
	},
	{
		_id: 11,
		logo: "./image/dodge_logo.png",
		image: "./image/dodge.png",
		product: "Dodge",
		count: 1,
		price: 5000,
	},
	{
		_id: 12,
		logo: "./image/ferrari_logo.png",
		image: "./image/ferrari.png",
		product: "Ferrari",
		count: 1,
		price: 15000,
	},
	{
		_id: 13,
		logo: "./image/fiat_logo.png",
		image: "./image/fiat.png",
		product: "Fiat",
		count: 1,
		price: 5000,
	},
	{
		_id: 14,
		logo: "./image/ford_logo.png",
		image: "./image/ford.png",
		product: "Ford",
		count: 1,
		price: 6000,
	},
	{
		_id: 15,
		logo: "./image/honda_logo.png",
		image: "./image/honda.png",
		product: "Honda",
		count: 1,
		price: 4000,
	},
	{
		_id: 16,
		logo: "./image/hyundai_logo.png",
		image: "./image/hyundai.png",
		product: "Hyundai",
		count: 1,
		price: 3500,
	},
	{
		_id: 17,
		logo: "./image/infiniti_logo.png",
		image: "./image/infiniti.png",
		product: "Infiniti",
		count: 1,
		price: 4500,
	},
	{
		_id: 18,
		logo: "./image/isuzu_logo.png",
		image: "./image/isuzu.png",
		product: "Isuzu",
		count: 1,
		price: 3000,
	},
	{
		_id: 19,
		logo: "./image/jeep_logo.png",
		image: "./image/jeep.png",
		product: "Jeep",
		count: 1,
		price: 12500,
	},
	{
		_id: 20,
		logo: "./image/kia_logo.png",
		image: "./image/kia.png",
		product: "Kia",
		count: 1,
		price: 1500,
	},
	{
		_id: 21,
		logo: "./image/lamborghini_logo.png",
		image: "./image/lamborghini.png",
		product: "Lamborghini",
		count: 1,
		price: 15000,
	},
	{
		_id: 22,
		logo: "./image/land_rover_logo.png",
		image: "./image/land_rover.png",
		product: "Land Rover",
		count: 1,
		price: 15500,
	},
	{
		_id: 23,
		logo: "./image/maserati_logo.png",
		image: "./image/maserati.png",
		product: "Maserati",
		count: 1,
		price: 15000,
	},
	{
		_id: 24,
		logo: "./image/porsche_logo.png",
		image: "./image/porsche.png",
		product: "Porsche",
		count: 1,
		price: 20000,
	},
	{
		_id: 25,
		logo: "./image/rolls_royce_logo.png",
		image: "./image/rolls_royce.png",
		product: "Rolls Royce",
		count: 1,
		price: 21000,
	},
	{
		_id: 26,
		logo: "./image/chevrolet_logo.png",
		image: "./image/chevrolet.png",
		product: "Chevrolet",
		count: 1,
		price: 9500,
	},
]